server:
  port: 9003

spring:
  datasource:
    url: jdbc:mysql://hh:3306/report?useSSL=false&characterEncoding=utf8
    username: hive
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  configuration:
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
    use-generated-keys: true
    cache-enabled: true

logging:
  level:
    cn:
      goldlone:
        commerce:
          dao: DEBUG
#  mapper-locations: classpath:mybatis/*.xml
